export const SITE = {
  website: "https://lyonmay.com/",
  author: "Lyon May",
  profile: "https://github.com/LyonMay",
  desc: "On all my grieves and reasons. A place to remember.",
  title: "On Grief And Reason",
  ogImage: "",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Shanghai",
} as const;
